version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: entrequiz-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: entrequiz
    ports:
      - "3306:3306"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  quiz-service:
    build: ./quiz-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
