services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - entrequiz-network

  quiz-service:
    build:
      context: ./quiz-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - entrequiz-network
    depends_on:
      - user-service

networks:
  entrequiz-network:
    driver: bridge
